name: vlmcsd
services:
  main-instance:
    ports:
      - 1688:1688
    healthcheck:
      test: nc -z 127.0.0.1 1688
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always
    image: theflightsims/vlmcsd:latest
